// Mock data for GOLD VAKUM SİSTEMLERİ

export const translations = {
  tr: {
    nav: {
      home: 'Ana Sayfa',
      products: 'Ürünler',
      about: 'Hakkımızda',
      contact: 'İletişim',
    },
    hero: {
      title: 'Profesyonel Endüstriyel Çözümler',
      subtitle: 'Yüksek kaliteli buhar jeneratörleri, vakum sistemleri ve endüstriyel presler',
      cta: 'Ürünleri Keşfedin',
      quote: 'Teklif Alın',
    },
    categories: {
      title: 'Ürün Kategorilerimiz',
      subtitle: 'Endüstriniz için en iyi çözümler',
    },
    features: {
      title: 'Neden GOLD?',
      quality: {
        title: 'Yüksek Kalite',
        desc: 'CE sertifikalı, dayanıklı ve uzun ömürlü ekipmanlar',
      },
      support: {
        title: 'Teknik Destek',
        desc: '7/24 profesyonel teknik destek ve bakım hizmeti',
      },
      warranty: {
        title: 'Garanti',
        desc: 'Tüm ürünlerimizde kapsamlı garanti ve yedek parça desteği',
      },
      global: {
        title: 'Global Teslimat',
        desc: 'Dünya çapında güvenli ve hızlı teslimat',
      },
    },
    products: {
      title: 'Ürünlerimiz',
      viewDetails: 'Detayları Gör',
      getQuote: 'Teklif Al',
      specifications: 'Teknik Özellikler',
      description: 'Ürün Açıklaması',
      features: 'Özellikler',
    },
    contact: {
      title: 'Teklif Alın',
      subtitle: 'Uzman ekibimiz size en uygun çözümü sunacaktır',
      name: 'Adınız Soyadınız',
      email: 'E-posta',
      phone: 'Telefon',
      company: 'Şirket Adı',
      product: 'İlgilendiğiniz Ürün',
      message: 'Mesajınız',
      send: 'Gönder',
      success: 'Mesajınız başarıyla gönderildi!',
    },
    footer: {
      company: 'GOLD VAKUM SİSTEMLERİ MAKİNA SANAYİ TİCARET LİMİTED ŞİRKETİ',
      rights: 'Tüm hakları saklıdır.',
      quick: 'Hızlı Linkler',
      contact: 'İletişim Bilgileri',
    },
  },
  en: {
    nav: {
      home: 'Home',
      products: 'Products',
      about: 'About Us',
      contact: 'Contact',
    },
    hero: {
      title: 'Professional Industrial Solutions',
      subtitle: 'High-quality steam generators, vacuum systems and industrial presses',
      cta: 'Explore Products',
      quote: 'Get Quote',
    },
    categories: {
      title: 'Our Product Categories',
      subtitle: 'Best solutions for your industry',
    },
    features: {
      title: 'Why GOLD?',
      quality: {
        title: 'High Quality',
        desc: 'CE certified, durable and long-lasting equipment',
      },
      support: {
        title: 'Technical Support',
        desc: '24/7 professional technical support and maintenance service',
      },
      warranty: {
        title: 'Warranty',
        desc: 'Comprehensive warranty and spare parts support for all products',
      },
      global: {
        title: 'Global Delivery',
        desc: 'Safe and fast delivery worldwide',
      },
    },
    products: {
      title: 'Our Products',
      viewDetails: 'View Details',
      getQuote: 'Get Quote',
      specifications: 'Technical Specifications',
      description: 'Product Description',
      features: 'Features',
    },
    contact: {
      title: 'Request a Quote',
      subtitle: 'Our expert team will provide you with the most suitable solution',
      name: 'Full Name',
      email: 'Email',
      phone: 'Phone',
      company: 'Company Name',
      product: 'Product of Interest',
      message: 'Your Message',
      send: 'Send',
      success: 'Your message has been sent successfully!',
    },
    footer: {
      company: 'GOLD VAKUM SİSTEMLERİ MAKİNA SANAYİ TİCARET LİMİTED ŞİRKETİ',
      rights: 'All rights reserved.',
      quick: 'Quick Links',
      contact: 'Contact Information',
    },
  },
  ar: {
    nav: {
      home: 'الصفحة الرئيسية',
      products: 'المنتجات',
      about: 'من نحن',
      contact: 'اتصل بنا',
    },
    hero: {
      title: 'حلول صناعية احترافية',
      subtitle: 'مولدات بخار وأنظمة فراغ ومكابس صناعية عالية الجودة',
      cta: 'استكشف المنتجات',
      quote: 'احصل على عرض أسعار',
    },
    categories: {
      title: 'فئات المنتجات',
      subtitle: 'أفضل الحلول لصناعتك',
    },
    features: {
      title: 'لماذا GOLD؟',
      quality: {
        title: 'جودة عالية',
        desc: 'معدات معتمدة من CE، متينة وطويلة الأمد',
      },
      support: {
        title: 'الدعم الفني',
        desc: 'دعم فني وصيانة احترافية على مدار الساعة',
      },
      warranty: {
        title: 'الضمان',
        desc: 'ضمان شامل ودعم قطع الغيار لجميع المنتجات',
      },
      global: {
        title: 'التسليم العالمي',
        desc: 'تسليم آمن وسريع في جميع أنحاء العالم',
      },
    },
    products: {
      title: 'منتجاتنا',
      viewDetails: 'عرض التفاصيل',
      getQuote: 'احصل على عرض أسعار',
      specifications: 'المواصفات الفنية',
      description: 'وصف المنتج',
      features: 'المميزات',
    },
    contact: {
      title: 'طلب عرض أسعار',
      subtitle: 'سيوفر لك فريق الخبراء لدينا الحل الأنسب',
      name: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      company: 'اسم الشركة',
      product: 'المنتج المهتم به',
      message: 'رسالتك',
      send: 'إرسال',
      success: 'تم إرسال رسالتك بنجاح!',
    },
    footer: {
      company: 'GOLD VAKUM SİSTEMLERİ MAKİNA SANAYİ TİCARET LİMİTED ŞİRKETİ',
      rights: 'جميع الحقوق محفوظة.',
      quick: 'روابط سريعة',
      contact: 'معلومات الاتصال',
    },
  },
  ru: {
    nav: {
      home: 'Главная',
      products: 'Продукция',
      about: 'О нас',
      contact: 'Контакты',
    },
    hero: {
      title: 'Профессиональные промышленные решения',
      subtitle: 'Высококачественные парогенераторы, вакуумные системы и промышленные прессы',
      cta: 'Изучить продукцию',
      quote: 'Запросить цену',
    },
    categories: {
      title: 'Категории продукции',
      subtitle: 'Лучшие решения для вашей отрасли',
    },
    features: {
      title: 'Почему GOLD?',
      quality: {
        title: 'Высокое качество',
        desc: 'Сертифицированное оборудование CE, прочное и долговечное',
      },
      support: {
        title: 'Техподдержка',
        desc: 'Профессиональная техподдержка и обслуживание 24/7',
      },
      warranty: {
        title: 'Гарантия',
        desc: 'Комплексная гарантия и поддержка запчастей для всей продукции',
      },
      global: {
        title: 'Глобальная доставка',
        desc: 'Безопасная и быстрая доставка по всему миру',
      },
    },
    products: {
      title: 'Наша продукция',
      viewDetails: 'Подробнее',
      getQuote: 'Запросить цену',
      specifications: 'Технические характеристики',
      description: 'Описание продукта',
      features: 'Особенности',
    },
    contact: {
      title: 'Запросить цену',
      subtitle: 'Наша команда экспертов предоставит вам наиболее подходящее решение',
      name: 'Полное имя',
      email: 'Эл. почта',
      phone: 'Телефон',
      company: 'Название компании',
      product: 'Интересующий продукт',
      message: 'Ваше сообщение',
      send: 'Отправить',
      success: 'Ваше сообщение успешно отправлено!',
    },
    footer: {
      company: 'GOLD VAKUM SİSTEMLERİ MAKİNA SANAYİ TİCARET LİMİTED ŞİRKETİ',
      rights: 'Все права защищены.',
      quick: 'Быстрые ссылки',
      contact: 'Контактная информация',
    },
  },
};

export const categories = [
  {
    id: 1,
    name: {
      tr: 'Buhar Jeneratörü',
      en: 'Steam Generator',
      ar: 'مولد البخار',
      ru: 'Парогенератор',
    },
    description: {
      tr: 'Profesyonel istim makinaları',
      en: 'Professional steam machines',
      ar: 'آلات بخار احترافية',
      ru: 'Профессиональные паровые машины',
    },
    image: 'https://customer-assets.emergentagent.com/job_00fb527f-13c0-4a88-8f54-3e96e9176e0d/artifacts/c3vefy9q_BT8A7957.jpg',
    slug: 'steam-generator',
  },
  {
    id: 2,
    name: {
      tr: 'Vakum Sistemleri',
      en: 'Vacuum Systems',
      ar: 'أنظمة الفراغ',
      ru: 'Вакуумные системы',
    },
    description: {
      tr: 'Masaüstü tekli cila makinası',
      en: 'Desktop single polishing machine',
      ar: 'آلة تلميع منفردة على سطح المكتب',
      ru: 'Настольная полировальная машина',
    },
    image: 'https://customer-assets.emergentagent.com/job_00fb527f-13c0-4a88-8f54-3e96e9176e0d/artifacts/m2s1wccc_BT8A8012.jpg',
    slug: 'vacuum-systems',
  },
  {
    id: 3,
    name: {
      tr: 'Endüstriyel Pres',
      en: 'Industrial Press',
      ar: 'مكبس صناعي',
      ru: 'Промышленный пресс',
    },
    description: {
      tr: 'İstim makinası entegre pres sistemleri',
      en: 'Steam machine integrated press systems',
      ar: 'أنظمة مكابس متكاملة مع آلة البخار',
      ru: 'Прессовые системы с интегрированной паровой машиной',
    },
    image: 'https://customer-assets.emergentagent.com/job_00fb527f-13c0-4a88-8f54-3e96e9176e0d/artifacts/wr1vvevf_BT8A8026.jpg',
    slug: 'industrial-press',
  },
];

export const products = [
  {
    id: 1,
    categoryId: 1,
    name: {
      tr: 'GOLD 3.5 KW Buhar Jeneratörü',
      en: 'GOLD 3.5 KW Steam Generator',
      ar: 'مولد بخار GOLD 3.5 كيلووات',
      ru: 'Парогенератор GOLD 3.5 кВт',
    },
    description: {
      tr: 'Kompakt ve güçlü buhar jeneratörü. Profesyonel kullanım için ideal. CE sertifikalı, paslanmaz çelik gövde, güvenlik vanası ve basınç göstergesi ile donatılmıştır.',
      en: 'Compact and powerful steam generator. Ideal for professional use. CE certified, stainless steel body, equipped with safety valve and pressure gauge.',
      ar: 'مولد بخار مدمج وقوي. مثالي للاستخدام المهني. معتمد من CE، هيكل من الفولاذ المقاوم للصدأ، مجهز بصمام أمان ومقياس ضغط.',
      ru: 'Компактный и мощный парогенератор. Идеален для профессионального использования. Сертифицирован CE, корпус из нержавеющей стали, оснащен предохранительным клапаном и манометром.',
    },
    specs: {
      power: '3.5 KW',
      voltage: '220V / 380V',
      capacity: '5 Litre',
      pressure: '4 Bar',
      weight: '15 kg',
    },
    features: {
      tr: [
        'Paslanmaz çelik kazan',
        'Otomatik su seviye kontrolü',
        'Güvenlik vanası',
        'Basınç göstergesi',
        'CE sertifikalı',
        'Kompakt tasarım',
      ],
      en: [
        'Stainless steel boiler',
        'Automatic water level control',
        'Safety valve',
        'Pressure gauge',
        'CE certified',
        'Compact design',
      ],
      ar: [
        'غلاية من الفولاذ المقاوم للصدأ',
        'تحكم تلقائي في مستوى الماء',
        'صمام أمان',
        'مقياس ضغط',
        'معتمد من CE',
        'تصميم مدمج',
      ],
      ru: [
        'Котел из нержавеющей стали',
        'Автоматический контроль уровня воды',
        'Предохранительный клапан',
        'Манометр',
        'Сертифицирован CE',
        'Компактный дизайн',
      ],
    },
    images: [
      'https://customer-assets.emergentagent.com/job_00fb527f-13c0-4a88-8f54-3e96e9176e0d/artifacts/c3vefy9q_BT8A7957.jpg',
      'https://customer-assets.emergentagent.com/job_00fb527f-13c0-4a88-8f54-3e96e9176e0d/artifacts/c1y3ohw2_BT8A7957.png',
    ],
    price: 'Fiyat için iletişime geçin',
  },
  {
    id: 2,
    categoryId: 1,
    name: {
      tr: 'GOLD 6 KW Buhar Jeneratörü',
      en: 'GOLD 6 KW Steam Generator',
      ar: 'مولد بخار GOLD 6 كيلووات',
      ru: 'Парогенератор GOLD 6 кВт',
    },
    description: {
      tr: 'Yüksek kapasiteli profesyonel buhar jeneratörü. Endüstriyel kullanım için özel olarak tasarlanmıştır. Güçlü motor ve uzun ömürlü yapısı ile kesintisiz çalışma sağlar.',
      en: 'High capacity professional steam generator. Specially designed for industrial use. Provides uninterrupted operation with powerful motor and long-lasting structure.',
      ar: 'مولد بخار احترافي عالي السعة. مصمم خصيصًا للاستخدام الصناعي. يوفر تشغيلًا متواصلًا مع محرك قوي وهيكل طويل الأمد.',
      ru: 'Профессиональный парогенератор высокой мощности. Специально разработан для промышленного использования. Обеспечивает бесперебойную работу благодаря мощному двигателю и долговечной конструкции.',
    },
    specs: {
      power: '6 KW',
      voltage: '380V',
      capacity: '10 Litre',
      pressure: '5 Bar',
      weight: '25 kg',
    },
    features: {
      tr: [
        'Yüksek kapasite',
        'Endüstriyel kullanım',
        'Dijital kontrol paneli',
        'Otomatik dolum sistemi',
        'Aşırı ısınma koruması',
        'Uzun ömürlü yapı',
      ],
      en: [
        'High capacity',
        'Industrial use',
        'Digital control panel',
        'Automatic filling system',
        'Overheat protection',
        'Long-lasting structure',
      ],
      ar: [
        'سعة عالية',
        'استخدام صناعي',
        'لوحة تحكم رقمية',
        'نظام ملء تلقائي',
        'حماية من الحرارة الزائدة',
        'هيكل طويل الأمد',
      ],
      ru: [
        'Высокая мощность',
        'Промышленное использование',
        'Цифровая панель управления',
        'Автоматическая система наполнения',
        'Защита от перегрева',
        'Долговечная конструкция',
      ],
    },
    images: [
      'https://customer-assets.emergentagent.com/job_00fb527f-13c0-4a88-8f54-3e96e9176e0d/artifacts/c3vefy9q_BT8A7957.jpg',
    ],
    price: 'Fiyat için iletişime geçin',
  },
  {
    id: 3,
    categoryId: 2,
    name: {
      tr: 'Masaüstü Tekli Cila Makinası',
      en: 'Desktop Single Polishing Machine',
      ar: 'آلة تلميع منفردة على سطح المكتب',
      ru: 'Настольная полировальная машина',
    },
    description: {
      tr: 'Kompakt ve kullanışlı masaüstü cila makinası. Ayakkabı, çanta ve deri ürünlerin cilası için mükemmel çözüm. Güçlü vakum sistemi ile toz ve kir emmesi yapar.',
      en: 'Compact and practical desktop polishing machine. Perfect solution for polishing shoes, bags and leather products. Dust and dirt extraction with powerful vacuum system.',
      ar: 'آلة تلميع مدمجة وعملية على سطح المكتب. حل مثالي لتلميع الأحذية والحقائب والمنتجات الجلدية. استخراج الغبار والأوساخ مع نظام فراغ قوي.',
      ru: 'Компактная и практичная настольная полировальная машина. Идеальное решение для полировки обуви, сумок и изделий из кожи. Удаление пыли и грязи с помощью мощной вакуумной системы.',
    },
    specs: {
      power: '0.75 KW',
      voltage: '220V',
      vacuum: 'Entegre vakum sistemi',
      dimensions: '40x30x35 cm',
      weight: '12 kg',
    },
    features: {
      tr: [
        'Kompakt tasarım',
        'Güçlü vakum sistemi',
        'Ayarlanabilir hız',
        'Sessiz çalışma',
        'Kolay temizlik',
        'Dayanıklı yapı',
      ],
      en: [
        'Compact design',
        'Powerful vacuum system',
        'Adjustable speed',
        'Quiet operation',
        'Easy cleaning',
        'Durable structure',
      ],
      ar: [
        'تصميم مدمج',
        'نظام فراغ قوي',
        'سرعة قابلة للتعديل',
        'تشغيل هادئ',
        'تنظيف سهل',
        'هيكل متين',
      ],
      ru: [
        'Компактный дизайн',
        'Мощная вакуумная система',
        'Регулируемая скорость',
        'Тихая работа',
        'Легкая очистка',
        'Прочная конструкция',
      ],
    },
    images: [
      'https://customer-assets.emergentagent.com/job_00fb527f-13c0-4a88-8f54-3e96e9176e0d/artifacts/m2s1wccc_BT8A8012.jpg',
      'https://customer-assets.emergentagent.com/job_00fb527f-13c0-4a88-8f54-3e96e9176e0d/artifacts/k331ts67_BT8A8015.png',
    ],
    price: 'Fiyat için iletişime geçin',
  },
  {
    id: 4,
    categoryId: 3,
    name: {
      tr: 'Endüstriyel Pres + İstim Makinası',
      en: 'Industrial Press + Steam Machine',
      ar: 'مكبس صناعي + آلة بخار',
      ru: 'Промышленный пресс + паровая машина',
    },
    description: {
      tr: 'Profesyonel kullanım için tasarlanmış endüstriyel pres ve istim makinası kombinasyonu. Tekstil, hazır giyim ve ayakkabı sektörü için ideal çözüm. Güçlü buhar sistemi ve hassas pres kontrolü.',
      en: 'Industrial press and steam machine combination designed for professional use. Ideal solution for textile, ready-to-wear and footwear industry. Powerful steam system and precise press control.',
      ar: 'مزيج من المكبس الصناعي وآلة البخار المصمم للاستخدام المهني. حل مثالي لصناعة النسيج والملابس الجاهزة والأحذية. نظام بخار قوي وتحكم دقيق في المكبس.',
      ru: 'Комбинация промышленного пресса и паровой машины, разработанная для профессионального использования. Идеальное решение для текстильной промышленности, производства готовой одежды и обуви. Мощная паровая система и точный контроль пресса.',
    },
    specs: {
      power: '2.2 KW',
      voltage: '380V',
      pressure: '6 Bar',
      table: '60x40 cm',
      weight: '85 kg',
    },
    features: {
      tr: [
        'Çift ayak pedal kontrol',
        'Güçlü buhar sistemi',
        'Ayarlanabilı basınç',
        'Geniş çalışma alanı',
        'Endüstriyel kullanım',
        'CE sertifikalı',
      ],
      en: [
        'Dual foot pedal control',
        'Powerful steam system',
        'Adjustable pressure',
        'Wide working area',
        'Industrial use',
        'CE certified',
      ],
      ar: [
        'تحكم بدواسة القدم المزدوجة',
        'نظام بخار قوي',
        'ضغط قابل للتعديل',
        'منطقة عمل واسعة',
        'استخدام صناعي',
        'معتمد من CE',
      ],
      ru: [
        'Управление двойной ножной педалью',
        'Мощная паровая система',
        'Регулируемое давление',
        'Широкая рабочая зона',
        'Промышленное использование',
        'Сертифицирован CE',
      ],
    },
    images: [
      'https://customer-assets.emergentagent.com/job_00fb527f-13c0-4a88-8f54-3e96e9176e0d/artifacts/wr1vvevf_BT8A8026.jpg',
    ],
    price: 'Fiyat için iletişime geçin',
  },
];
